name: CI build App for Mac with CMake and Qt5

on:
  push:
  release:
    types:
      - created

jobs:

  build-unix-qt5:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            QT_FILE: qtBase_5.15.1_mac.zip
            LIBDE265_REMOTE: libde265.dylib
            LIBDE265_LOCAL: libde265-internals.dylib
            ARTIFACT_NAME: YUView-Mac.zip
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

##########################################################################################
############################### Packages build by us: Qt, libde265  ######################
##########################################################################################

    - name: Install Qt base
      run: |
        cd $HOME
        mkdir -p YUViewQt
        cd YUViewQt
        curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtBase-5.15.1/${{matrix.QT_FILE}} -o Qt.zip
        unzip -qa Qt.zip
      shell: bash

    - name: Install libde265
      run: |
        cd $HOME
        curl -L https://github.com/ChristianFeldmann/libde265/releases/download/v1.1/${{matrix.LIBDE265_REMOTE}} -o ${{matrix.LIBDE265_LOCAL}}
        curl -L https://raw.githubusercontent.com/ChristianFeldmann/libde265/master/COPYING -o libde265License.txt
        find .
      shell: bash

##########################################################################################
############################### Build YUView #############################################
##########################################################################################

    - name: Build Linux/Mac
      run: |
        pwd
        cd $GITHUB_WORKSPACE
        mkdir build
        cd build
        cmake  -DCMAKE_PREFIX_PATH="$HOME/YUViewQt/Qt" -DCMAKE_INSTALL_PREFIX=/usr ..
        cmake --build . --parallel $(nproc)
        # list files for debug
        find .
      shell: bash

##########################################################################################
############################### Unit tests ###############################################
##########################################################################################

    - name: Run unit tests
      run: |
        cd $GITHUB_WORKSPACE/build
        ctest --output-on-failure
        # ctest --output-on-failure --debug --extra-verbose
      shell: bash

##########################################################################################
############################### Packaging YUView, Installers #############################
##########################################################################################

    - name: Build App (Mac)
      run: |
        cd $HOME/YUViewQt
        curl -L https://github.com/ChristianFeldmann/YUViewQt/releases/download/QtDeployTools-5.15.1/qtTools_5.15.1_mac.zip -o deployQt.zip
        unzip -qa deployQt.zip
        cp Qttools/bin/macdeployqt Qt/bin/macdeployqt
        strip Qt/bin/macdeployqt
        cd $GITHUB_WORKSPACE
        $HOME/YUViewQt/Qt/bin/macdeployqt build/YUView.app -always-overwrite -verbose=2
        cp $HOME/${{matrix.LIBDE265_LOCAL}} build/YUView.app/Contents/MacOS/.
        cd build
        # Zip
        zip -r ${{matrix.ARTIFACT_NAME}} YUView.app/
        mkdir $GITHUB_WORKSPACE/artifacts
        cp ${{matrix.ARTIFACT_NAME}} $GITHUB_WORKSPACE/artifacts/
      if: matrix.os == 'macos-10.15' || matrix.os == 'macos-11.0'

##########################################################################################
############################### Upload ###################################################
##########################################################################################

    - name: Upload Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: artifacts/${{matrix.ARTIFACT_NAME}}
        asset_name: ${{matrix.ARTIFACT_NAME}}
        asset_content_type: application/zip
      if: github.event_name == 'release' && matrix.os == 'macos-10.15'

  # How to upload files to the release:
  # https://github.com/Blacksmoke16/oq/pull/47/files#diff-082c28d748ad2e3eecc5508d740d9417R9-R29
  # Mime type list
  # https://www.iana.org/assignments/media-types/media-types.xhtml
